server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        # Always load the latest version of the page while developing.
        add_header Cache-Control "no-cache";
    }
}
